apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
 containers:
   - name: c1
     image: alpine
     env:
      - name: firstName
        value: "chaithanya" 
      - name: lastName
        value: "Dasari"  
     command: 
      - "sh"
      - "-c"
      - 'while true ;do echo "my name is ${lastName}${firstName} " ; sleep 5 ; done'
