apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
 containers:
   - name: c1
     image: alpine
     env:
      - name: name
        value: "chaithanyaa" 
     command: 
      - "sh"
      - "-c"
      - 'while true ;do echo "$name" ; sleep 5 ; done'
