apiVersion: v1
kind: Pod
metadata:
  name: nginx_pod
  labels:
    name: nginx
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
    ports:
      - containerPort: 80
        name: nginx_port

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    name: nginx
  ports:
  - port: 80
    targetPort: nginx_pod

