apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    name: &labels nginx
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
    ports:
      - containerPort: 80
        name: nginxport

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    name: *labels
  ports:
  - port: 80
    targetPort: nginxport

# This is comment
Description: >
 environment: &using 
    name: dev
    project: roboshop
 environment: *using
# ----------------  

Descriptio: >
 environment: &using 
    name: dev
    project: roboshop
 environment: 
    <<: *using
    colud: aws

#-------------------------    
   

