apiVersion: v1
kind: Pod
metadata:
  name: &podname nginxpod
  labels:
    name: *podname
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
    ports:
      - containerPort: 80
        name: nginxport

---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    name: nginxpod
  ports:
  - port: 80
    targetPort: nginxport

    
   

